FLUSH TABLES;
FLUSH STATUS;

SELECT * FROM customer LIMIT 15;
SELECT COUNT(*) FROM customer WHERE C_NATIONKEY = 15;
SELECT COUNT(*) FROM customer WHERE C_NATIONKEY = 13;

SELECT * FROM orders LIMIT 10;
SELECT * FROM orders where O_CUSTKEY = 36901;
SELECT * FROM orders where O_CUSTKEY = 78002;
SELECT * FROM orders where O_CUSTKEY = 123314;
SELECT O_CUSTKEY, COUNT(O_CUSTKEY) FROM orders GROUP BY O_CUSTKEY;
SELECT O_CUSTKEY, COUNT(O_CUSTKEY) as count FROM orders GROUP BY O_CUSTKEY HAVING count = 1;

SELECT * FROM orders where O_CUSTKEY = 1910;

SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';

#EXPLAIN
EXPLAIN  SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
EXPLAIN SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';

#EXPLAIN JSON
EXPLAIN FORMAT=JSON SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
EXPLAIN FORMAT=JSON SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';

#EXPLAIN TREE
EXPLAIN FORMAT=TREE SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
EXPLAIN FORMAT=TREE SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';

#EXPLAIN ANALYZE
EXPLAIN ANALYZE SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
EXPLAIN ANALYZE SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';
