FLUSH TABLES;
FLUSH STATUS;

# ID: 1
SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';

#EXPLAIN
EXPLAIN  SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
EXPLAIN SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';

#EXPLAIN JSON
EXPLAIN FORMAT=JSON SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
EXPLAIN FORMAT=JSON SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';

#EXPLAIN TREE
EXPLAIN FORMAT=TREE SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
EXPLAIN FORMAT=TREE SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';

#EXPLAIN ANALYZE
EXPLAIN ANALYZE SELECT * FROM orders where O_ORDERPRIORITY = '5-LOW' AND O_CUSTKEY = 1910;
EXPLAIN ANALYZE SELECT * FROM orders where O_CUSTKEY = 1910 AND O_ORDERPRIORITY = '5-LOW';

EXPLAIN TABLE orders;

# -------------------------------------------------------
# PRIMARY KEY TESTS, WHERE PRIMARY KEY IS INDEX
# ID: 2
EXPLAIN SELECT * FROM orders WHERE O_ORDERKEY = 1858 AND O_ORDERSTATUS = 'O';
EXPLAIN FORMAT=JSON SELECT * FROM orders WHERE O_ORDERKEY = 1858 AND O_ORDERSTATUS = 'O';
EXPLAIN FORMAT=TREE SELECT * FROM orders WHERE O_ORDERKEY = 1858 AND O_ORDERSTATUS = 'O';
EXPLAIN ANALYZE SELECT * FROM orders WHERE O_ORDERKEY = 1858 AND O_ORDERSTATUS = 'O';

EXPLAIN SELECT * FROM orders WHERE O_ORDERSTATUS = 'O' AND O_ORDERKEY = 1858;
EXPLAIN FORMAT=JSON SELECT * FROM orders WHERE O_ORDERSTATUS = 'O' AND O_ORDERKEY = 1858;
EXPLAIN FORMAT=TREE SELECT * FROM orders WHERE O_ORDERSTATUS = 'O' AND O_ORDERKEY = 1858;
EXPLAIN ANALYZE SELECT * FROM orders WHERE O_ORDERSTATUS = 'O' AND O_ORDERKEY = 1858;

EXPLAIN SELECT * FROM orders WHERE O_ORDERKEY = 259 AND O_ORDERSTATUS = 'F';
EXPLAIN FORMAT=JSON SELECT * FROM orders WHERE O_ORDERKEY = 259 AND O_ORDERSTATUS = 'F';
EXPLAIN FORMAT=TREE SELECT * FROM orders WHERE O_ORDERKEY = 259 AND O_ORDERSTATUS = 'F';
EXPLAIN ANALYZE SELECT * FROM orders WHERE O_ORDERKEY = 259 AND O_ORDERSTATUS = 'F';

EXPLAIN SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 259;
EXPLAIN FORMAT=JSON SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 259;
EXPLAIN FORMAT=TREE SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 259;
EXPLAIN ANALYZE SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 259;

# To be done
EXPLAIN SELECT * FROM orders WHERE O_ORDERKEY = 290 AND O_ORDERSTATUS = 'F';
EXPLAIN FORMAT=JSON SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 290;
EXPLAIN FORMAT=TREE SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 290;
EXPLAIN ANALYZE SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 290;

EXPLAIN SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 290;
EXPLAIN FORMAT=JSON SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 290;
EXPLAIN FORMAT=TREE SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 290;
EXPLAIN ANALYZE SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 290;


SELECT * FROM orders WHERE O_ORDERSTATUS = 'F' AND O_ORDERKEY = 64;